"""initial scaffold schema

Revision ID: 08adec2dab35
Revises:
Create Date: 2026-07-10 01:16:58.152826
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "08adec2dab35"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=120), nullable=False),
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "key", name="uq_idempotency_scope_key"),
    )
    op.create_index(
        "ix_idempotency_expires_at", "idempotency_records", ["expires_at"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_type"), "outbox_events", ["aggregate_type"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_event_type"), "outbox_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_occurred_at"), "outbox_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_processed_at"), "outbox_events", ["processed_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("GUEST", "REGISTERED", name="userkind", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("primary_muscle_group", sa.String(length=80), nullable=False),
        sa.Column("equipment", sa.String(length=80), nullable=False),
        sa.Column(
            "tracking_type",
            sa.Enum(
                "REPS_WEIGHT",
                "REPS",
                "DURATION",
                "DISTANCE_DURATION",
                name="trackingtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column(
            "sync_status",
            sa.Enum(
                "LOCAL_ONLY",
                "PENDING",
                "SYNCING",
                "SYNCED",
                "FAILED",
                "CONFLICT",
                name="syncstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_exercises_owner_deleted", "exercises", ["owner_user_id", "deleted_at"], unique=False
    )
    op.create_index(
        "ix_exercises_owner_updated", "exercises", ["owner_user_id", "updated_at"], unique=False
    )
    op.create_table(
        "guest_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_guest_sessions_expires_at"), "guest_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_guest_sessions_user_id"), "guest_sessions", ["user_id"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column(
            "unit_system",
            sa.Enum("METRIC", "IMPERIAL", name="unitsystem", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "onboarding_status",
            sa.Enum(
                "NOT_STARTED",
                "SKIPPED",
                "IN_PROGRESS",
                "COMPLETED",
                name="onboardingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "sync_status",
            sa.Enum(
                "LOCAL_ONLY",
                "PENDING",
                "SYNCING",
                "SYNCED",
                "FAILED",
                "CONFLICT",
                name="syncstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_profiles_updated_at"), "profiles", ["updated_at"], unique=False)
    op.create_table(
        "workouts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="workoutstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column(
            "sync_status",
            sa.Enum(
                "LOCAL_ONLY",
                "PENDING",
                "SYNCING",
                "SYNCED",
                "FAILED",
                "CONFLICT",
                name="syncstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workouts_owner_updated", "workouts", ["owner_user_id", "updated_at"], unique=False
    )
    op.create_table(
        "workout_exercises",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workout_id", "position", name="uq_workout_exercise_position"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workout_exercises")
    op.drop_index("ix_workouts_owner_updated", table_name="workouts")
    op.drop_table("workouts")
    op.drop_index(op.f("ix_profiles_updated_at"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_guest_sessions_user_id"), table_name="guest_sessions")
    op.drop_index(op.f("ix_guest_sessions_expires_at"), table_name="guest_sessions")
    op.drop_table("guest_sessions")
    op.drop_index("ix_exercises_owner_updated", table_name="exercises")
    op.drop_index("ix_exercises_owner_deleted", table_name="exercises")
    op.drop_table("exercises")
    op.drop_table("users")
    op.drop_index(op.f("ix_outbox_events_processed_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_occurred_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_event_type"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_type"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_idempotency_expires_at", table_name="idempotency_records")
    op.drop_table("idempotency_records")
    # ### end Alembic commands ###
